apiVersion: v1
kind: Pod
metadata:
  name: blink
spec:
  containers:
    - name: blink
      image: cgshome2/rpi-led-blink 
      securityContext:
        privileged: true
  nodeSelector:
    kubernetes.io/arch: arm64
