apiVersion: v1
kind: Pod
metadata:
  name: rpi-led-blink
spec:
  containers:
    - name: rpi-led-blink
      image: cgshome2/rpi-led-blink 
      securityContext:
        privileged: true      
  nodeSelector:
    kubernetes.io/arch: arm64
