name: cgshome2/rpi-led-blink

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo Hello, world!
      - name: multiline script
        run: |
          git --version
          python --version
          
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/led/blink
    steps:
      - name: checkout 
        uses: actions/checkout@v2
        
      - name: login to docker hub
        uses: docker/login-action@v1
        with: 
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Inspect builder
        run: |
          echo Platforms: ${{ steps.buildx.outputs.platforms }}
          
      - name: Build
        run: |
          docker buildx build --push \ # will run buildx
          --tag cgshome2/rpi-led-blink:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .

