name: build cgshome2/rpi-led-blink

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: ./src/rpi/blink
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2
        
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
          
      - name: login to docker hub
        uses: docker/login-action@v1
        with: 
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
        
      - name: build the image
        run: |
          docker buildx build --push \
          --tag cgshome2/rpi-led-blink:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
